### ISSUE TITLE
Feature Request: Define HTTP Status Code for Maintenance Page

### ISSUE THREAD

**Issue by darnux** [selvinortiz/craft-plugin-patrol#1]
Would be great if it were possible to set HTTP Status Code (e.g. HTTP 503) for redirects to maintenance pages due to SEO/SearchEngine reasons.

**Comment by brandonkelly** [comment]
What do you mean by “maintenance pages” ?

**Comment by selvinortiz** [comment]
@darnux I'm adding this to the queue, will add it soon.

**Comment by selvinortiz** [comment]
@darnux I'll be adding support for this on the next release I have planned before submitting Patrol to the plugin store.

**Comment by selvinortiz** [comment]
@darnux You can now do this in the latest release of Patrol https://github.com/selvinortiz/craft-plugin-patrol/releases/tag/3.1.0

However, rather the controlling the redirect status, you control the response status.

You can set `maintenanceModePageUrl` to `null` and set `maintenanceModeResponseStatusCode` to `505`. You would then just make sure that you have `503.html` in your templates if you wan to show the user something, rather than a plain server error.
