### ISSUE TITLE
Way to disable interface from Craft CP?

### ISSUE THREAD

**Issue by marcushouse** [selvinortiz/craft-plugin-patrol#8]
Hey mate, Another quick one. In the Craft 2 version, there was an enableCpTab option. Essentially I want to force all configs to be done fie config files rather than in the CP.

Is there a way to force the settings to be hidden / removed?

**Comment by selvinortiz** [comment]
@marcushouse I'm planning on adding back that setting on the next release. Just with a different name for Craft 3 (`enableCpSection`) to align with new conventions.

The new release might be a week out or so.

With the new setting, as it was the case in the C2 version, the settings are still there, just no easy way for someone to get to.

One more thing... file configs override cp configs. So if people can see a setting in the cp that it's being managed via a config, they won't be able to change it.

**Comment by engram-design** [comment]
No longer required as of [4.0.0](https://github.com/verbb/patrol/releases/tag/4.0.0) where the CP page has been removed entirely. There's no need to show the page in the control panel due to only plugin settings being able to be managed, which can (typically) only be done in development environments, or at least with `allowAdminChanges = true`.

For the most part, This page is no longer required (you can still access things via Settings > Patrol).
